# Generated by Django 6.0 on 2025-12-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='download_url',
            field=models.URLField(blank=True, help_text='Direct download link for the movie file', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, help_text='Short summary of the plot'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='featured',
            field=models.BooleanField(default=False, help_text='Show in the big banner?'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.JSONField(default=list, help_text="List of genres e.g. ['Action', 'Sci-Fi']"),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(help_text='Link to the poster image'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(default=0.0, help_text='IMDb rating (0-10)'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(help_text='The name of the movie', max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, help_text='Link to YouTube trailer or video file', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trending',
            field=models.BooleanField(default=False, help_text="Show in 'Trending Now'?"),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(help_text='Release year'),
        ),
    ]
