# Generated by Django 6.0 on 2025-12-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_download_url_alter_movie_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='screenshot_1',
            field=models.URLField(blank=True, help_text='Screenshot URL 1', null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='screenshot_2',
            field=models.URLField(blank=True, help_text='Screenshot URL 2', null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='screenshot_3',
            field=models.URLField(blank=True, help_text='Screenshot URL 3', null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='screenshot_4',
            field=models.URLField(blank=True, help_text='Screenshot URL 4', null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='screenshot_5',
            field=models.URLField(blank=True, help_text='Screenshot URL 5', null=True),
        ),
    ]
