# Generated by Django 6.0 on 2025-12-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_screenshot_1_movie_screenshot_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='languages',
            field=models.JSONField(default=list, help_text="List of available languages e.g. ['Hindi', 'English']"),
        ),
    ]
